// api/exerbud-pdf.js

const PDFDocument = require("pdfkit");
const https = require("https");

const LOGO_URL = "https://cdn.shopify.com/s/files/1/0731/9882/9803/files/exerbudlogoblackfavicon_6093c857-65ce-4c64-8292-0597a6c6cf17.png?v=1763185899";

function fetchImageBuffer(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (resp) => {
        if (resp.statusCode !== 200) {
          return reject(new Error("Failed to load image: " + resp.statusCode));
        }
        const data = [];
        resp.on("data", (chunk) => data.push(chunk));
        resp.on("end", () => resolve(Buffer.concat(data)));
      })
      .on("error", reject);
  });
}

module.exports = async (req, res) => {
  // Basic CORS (mirror exerbud-ai.js)
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Parse body
  let body = req.body;
  if (typeof body === "string") {
    try {
      body = JSON.parse(body);
    } catch (err) {
      return res.status(400).json({ error: "Invalid JSON in request body" });
    }
  }

  if (!body || typeof body !== "object") {
    return res
      .status(400)
      .json({ error: "Request body must be a JSON object" });
  }

  const content = (body.content || "").trim();
  const title = (body.title || "").trim() || "Your Exerbud Plan";

  if (!content) {
    return res.status(400).json({ error: "Missing 'content' in body" });
  }

  try {
    // Response headers for download
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      'attachment; filename="exerbud-plan.pdf"'
    );

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    // Stream PDF directly to response
    doc.pipe(res);

    // Try to load and render logo from remote URL
    try {
      const logoBuffer = await fetchImageBuffer(LOGO_URL);
      if (logoBuffer) {
        doc.image(logoBuffer, 50, 40, { width: 120 });
        doc.moveDown(2.2);
      }
    } catch (e) {
      console.warn("Exerbud PDF: logo load failed:", e.message);
      // Safe to continue without logo
      doc.moveDown(1.0);
    }

    // Header text
    doc
      .fontSize(18)
      .font("Helvetica-Bold")
      .text("Exerbud – Workout / Training Plan", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(13)
      .font("Helvetica")
      .text(title, { align: "center" })
      .moveDown(1.5);

    // --- Simple markdown-ish formatting of the content ---
    const lines = content.split(/\r?\n/);

    const normalFont = () => {
      doc.font("Helvetica").fontSize(11);
    };

    lines.forEach((rawLine) => {
      const line = rawLine.trim();

      if (!line) {
        doc.moveDown(0.4);
        return;
      }

      // Headings
      if (line.startsWith("### ")) {
        doc
          .font("Helvetica-Bold")
          .fontSize(12)
          .text(line.slice(4))
          .moveDown(0.25);
        normalFont();
        return;
      }

      if (line.startsWith("## ")) {
        doc
          .font("Helvetica-Bold")
          .fontSize(13)
          .text(line.slice(3))
          .moveDown(0.25);
        normalFont();
        return;
      }

      if (line.startsWith("# ")) {
        doc
          .font("Helvetica-Bold")
          .fontSize(14)
          .text(line.slice(2))
          .moveDown(0.3);
        normalFont();
        return;
      }

      // Bullet points "- ..."
      if (line.startsWith("- ")) {
        normalFont();
        const text = line.slice(2);
        doc.text("• " + text, {
          continued: false,
        });
        return;
      }

      // Default paragraph
      normalFont();
      doc.text(line, { align: "left" }).moveDown(0.1);
    });

    // Footer
    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#888888")
      .text("Generated by Exerbud AI", { align: "center" });

    doc.end();
  } catch (err) {
    console.error("Exerbud PDF backend error:", err);
    if (!res.headersSent) {
      return res.status(500).json({ error: "Failed to generate PDF" });
    }
  }
};
