// api/exerbud-pdf.js
// Creates a simple, nicely formatted PDF from the last plan

const PDFDocument = require("pdfkit");
const https = require("https");

const LOGO_URL =
  "https://cdn.shopify.com/s/files/1/0731/9882/9803/files/exerbudlogoblackfavicon_6093c857-65ce-4c64-8292-0597a6c6cf17.png?v=1763185899";

function fetchImageBuffer(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          return reject(new Error("Failed to fetch logo, status " + res.statusCode));
        }
        const data = [];
        res.on("data", (chunk) => data.push(chunk));
        res.on("end", () => resolve(Buffer.concat(data)));
      })
      .on("error", reject);
  });
}

function writePlanContent(doc, content) {
  const lines = String(content || "").split(/\r?\n/);

  lines.forEach((lineRaw) => {
    const line = lineRaw.replace(/\s+$/g, "");
    const trimmed = line.trim();

    if (!trimmed) {
      doc.moveDown(0.4);
      return;
    }

    // Horizontal rule
    if (trimmed === "---") {
      doc.moveDown(0.3);
      doc
        .moveTo(doc.x, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .strokeColor("#dddddd")
        .lineWidth(1)
        .stroke()
        .strokeColor("#000000")
        .moveDown(0.4);
      return;
    }

    // Headings: #, ##, ###, ####
    const headingMatch = trimmed.match(/^(#{1,6})\s+(.*)$/);
    if (headingMatch) {
      const level = headingMatch[1].length;
      const text = headingMatch[2];

      const baseSize = 14;
      const size = Math.max(12, baseSize + (3 - Math.min(level, 3)));

      doc.moveDown(0.4);
      doc.font("Helvetica-Bold").fontSize(size).text(text, { width: 500 });
      doc.font("Helvetica").fontSize(12);
      return;
    }

    // Bullet list items: -, *, •
    if (/^[-*•]\s+/.test(trimmed)) {
      const bulletText = trimmed.replace(/^[-*•]\s+/, "");
      doc
        .font("Helvetica")
        .fontSize(12)
        .text("• " + bulletText, {
          width: 500,
          indent: 18,
        });
      return;
    }

    // Fallback normal paragraph
    doc.font("Helvetica").fontSize(12).text(trimmed, {
      width: 500,
    });
  });
}

module.exports = async (req, res) => {
  // Basic CORS
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  let body = req.body;
  if (typeof body === "string") {
    try {
      body = JSON.parse(body);
    } catch (err) {
      return res.status(400).json({ error: "Invalid JSON in request body" });
    }
  }

  const content = body?.content || "";
  const title = (body?.title || "Current plan from Exerbud").trim();

  try {
    // Fetch logo
    const logoBuffer = await fetchImageBuffer(LOGO_URL);

    // Create PDF
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, left: 50, right: 50, bottom: 60 },
    });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader(
        "Content-Disposition",
        'attachment; filename="exerbud-plan.pdf"'
      );
      res.status(200).send(pdfBuffer);
    });

    // Header with logo & brand
    try {
      doc.image(logoBuffer, 50, 40, { width: 40 });
    } catch (e) {
      console.error("Failed to draw logo in PDF:", e);
    }

    doc
      .font("Helvetica-Bold")
      .fontSize(18)
      .text("EXERBUD", 100, 46, { continued: false });

    doc.moveDown(1.4);
    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .text(title, { width: 500 });

    doc.moveDown(0.5);
    doc
      .font("Helvetica")
      .fontSize(10)
      .fillColor("#555555")
      .text("Generated by Exerbud AI", { width: 500 });

    doc.fillColor("#000000");
    doc.moveDown(1);

    // Body
    writePlanContent(doc, content);

    doc.end();
  } catch (err) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: "Failed to generate PDF." });
  }
};
